name: CI_teste

on: 
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: baixar o local
              uses: actions/checkout@v3

            - name: ðŸ“‚ Sync files
              uses: SamKirkland/FTP-Deploy-Action@v4.3.6
              with:
                server: f28-preview.awardspace.net
                username: ${{ secrets.FTP_USERNAME }}
                password: ${{ secrets.FTP_PASSWORD }}
                server-dir: /
                local-dir: /0tester
                protocol: ftp
                port: 21


